### ISSUE TITLE
windows compile errors

### ISSUE THREAD

**Issue by michaeldsmith** [ampas/CTL#106]
Windows compile errors using Visual Studio 2019 with OpenEXR 2.5.8

1) \CTL\lib\dpx\dpx_util.cc(58,10): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
2) \CTL\lib\dpx\dpx_rw.cc(129,6): error C3861: 'strncasecmp': identifier not found
3) \CTL\lib\IlmCtl\CtlExc.cpp(58,10): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
4) \CTL\lib\IlmCtl\CtlTypeStorage.cpp(67,10): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory
5) \CTL\lib\IlmCtl\CtlRcPtr.h(246,27): error C2512: 'IlmThread_2_5::Lock::Lock': no appropriate default constructor available
6) \CTL\lib\IlmCtl\CtlRcPtr.h(247,1): error C2027: use of undefined type 'Ctl::StatementNode'
7) \CTL\ctlrender\main.cc(59,10): fatal error C1083: Cannot open include file: 'sys/param.h': No such file or directory
8) \CTL\ctlrender\main.hh(59,10): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
9) \CTL\ctlrender\transform.cc(597,13): error C3861: 'strcasecmp': identifier not found
10) \CTL\ctlrender\tiff_file.cc(61,10): fatal error C1083: Cannot open include file: 'sys/param.h': No such file or directory

**Comment by michaeldsmith** [comment]
11) \CTL\lib\IlmCtl\CtlType.cpp(90): message : see reference to class template instantiation '__vcrt_assert_va_start_is_not_reference<const std::string &>' being compiled

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vadefs.h(194,62): error C2338: va_start argument must not have reference type and must not be parenthesized

**Comment by michaeldsmith** [comment]
when using windows compile with OpenEXR 3.1 there are additional errors:

12) \CTL\lib\IlmCtl\CtlRcPtr.h(218,12): error C2039: 'Mutex': is not a member of 'IlmThread' [D:\a\CTL\CTL\build\lib\IlmCtl\IlmCtl.vcxproj]

13) \CTL\lib\IlmCtl\CtlInterpreter.cpp(229,18): error C2512: 'IlmThread_3_1::Lock::Lock': no appropriate default constructor available [D:\a\CTL\CTL\build\lib\IlmCtl\IlmCtl.vcxproj]

14) \CTL\lib\IlmCtl\CtlInterpreter.cpp(199,23): error C2039: 'mutex': is not a member of 'Ctl::`anonymous-namespace'::ModulePathsData' [D:\a\CTL\CTL\build\lib\IlmCtl\IlmCtl.vcxproj]

**Comment by michaeldsmith** [comment]
Windows Debug Error Run-Time Check Failure no.3 - using Visual Studio 2019 with OpenEXR 2.5.8

15. \CTL\ctlrender\tiff_file.cc - Line 613 - Run-time Check Failure - The variable 'channel' is being used without being initialized
